### ISSUE TITLE
[VM or Radeon graphics] No login prompt with Mesa version 23.3.0-1pop0-1702935939-22.04-67e417a

### ISSUE THREAD

**Issue by zphelj** [pop-os/mesa#26] opened 2023-12-26 21:09 UTC
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

- libegl-mesa0
- libgmb1
- libgl1-mesa-dri
- libglapi-mesa
- libglx-mesa0
- libxatracker2 

Impacted version of each is 23.3.0-1pop0-1702935939-22.04-67e417a

**Issue/Bug Description:**

Running as a VM under Proxmox 8.1.3 I've determined that when these packages are upgraded to version 23.3.0-1pop0-1702935939-22.04-67e417a the system starts normally however the login prompt does not appear; it's a black screen with a mouse pointer.   This occurs using Spice (virtviewer) on Windows and Linux as well as noVNC web based console viewer.  No intervention I could find brings up a GUI login prompt and CTRL-ALT-F3 does not switch to the text console. The systems are accessible via SSH.

With a system using these 6 packages at version level 23.1.3-1pop0-1689084530-22.04-0618746 the behavior is as expected.

**Steps to reproduce (if you know):**

Install using POP OS defaults into a new VM and upgrade all packages EXCEPT those 6.  Verify normal operation. 
Shutdown the system and take a snapshot.
Reboot, upgrade the 6 packages to the impacted version, restart.

**Expected behavior:**

The system should boot to the GUI login screen and CTRL-ALT-F3 should be functional.

**Other Notes:**

I've tried this on two existing VM's and installed a new instance using a CDROM image 'pop-os_22.04_amd64_intel_35.iso' to do further testing with and isolate the issue to the 6 packages from that specific release and verify the issue was reproducible from a new install.  If you want to test with Spice you will need to intall package spice-vdagent.

Hope this report is useful, thanks!

**Comment by Matt-PMCT** [comment] 2023-12-28 00:21
I believe that I'm experiencing this issue as well. I ran system updates today and rebooted. Now I get nothing but a black screen, and CTRL-ALT-F3 does nothing. I can use noVNC from ProxMox, and the NoMachine client still connects. Unfortunately, I did not have remote SSH enabled, so at this point, I have absolutely no way of accessing the machine other than staring at a black screen with a mouse cursor. EDIT: I did get it boot to recovery by holding spacebar, was able to get necessary files off the machine.

**Comment by rquinlivan** [comment] 2023-12-28 02:54
I'm seeing the same issue. Booting OS lands me on a blank black screen with a mouse cursor. Bluetooth actually works on this screen, so I can move the mouse cursor, but there are no prompts, no shell, cannot escape to shell either.

**Comment by LightTemplar** [comment] 2023-12-28 04:41
Same here. I tried also refresh install + update => led to black screen again.

**Comment by chrisfonte** [comment] 2023-12-28 15:59
From here:

https://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package

Found this:

apt
Hold a package:

sudo apt-mark hold <package-name>
Remove the hold:

sudo apt-mark unhold <package-name>
Show all packages on hold:

sudo apt-mark showhold

So, to hold the packages mentioned in the github above from udating:

sudo apt-mark hold libegl-mesa0 libgmb1 libgl1-mesa-dri libglapi-mesa libglx-mesa0 libxatracker2

I'm going to try this, do an update, and see what happens.  Will report back.

**Comment by chrisfonte** [comment] 2023-12-28 16:13
So, with Pop!_OS in a VM after running updates yesterday, I restored a snapshot from October 23.  I then held the packages mentioned in this issue using the method I posted above.  I then did an update.  Upon rebooting the VM, the issue does not occur.

I will continue to monitor this thread to see if there is a permanent fix in an update, and will unold the packages and do an update at that time.

**Comment by LightTemplar** [comment] 2023-12-28 16:17
> libgmb1

Should be `libgbm1` - there was a typo.

**Comment by LightTemplar** [comment] 2023-12-28 17:10
> sudo apt-mark hold libegl-mesa0 libgbm1 libgl1-mesa-dri libglapi-mesa libglx-mesa0 libxatracker2

I tried it, and at least could load login promt, but still couldn't login - it threw me out. Even fresh created test user.

**Comment by chrisfonte** [comment] 2023-12-28 17:39
@jacobgkau The same issue I had was in XCP-ng so it's not just Proxmox...

**Comment by chrisfonte** [comment] 2023-12-28 17:41
It should be tested but at least one user in this thread reports the same issue on System76 hardware.

https://www.reddit.com/r/pop_os/comments/18sdlxb/black_screen/

**Comment by jacobgkau** [comment] 2023-12-28 18:50
@chrisfonte Thanks for mentioning XCP-ng. The Reddit thread you linked to has a mention of Hyper-V and one of Proxmox, in addition to one apparent Thelio owner. System76 hardware owners should reach out to the [support team](https://support.system76.com/). For now, this issue seems mostly related to VMs (it's unclear whether that Thelio owner's issue is actually the same one with no logs).

**Comment by jacobgkau** [comment] 2023-12-28 18:54
If anyone else does experience this on bare metal hardware, the specific GPU(s) you're using would be relevant information. (If a customer opens a case with our support team, then they'll be able to see the config from the order.)

**Comment by bastouf** [comment] 2023-12-28 18:59
I have same issue on my professionnal (!) laptop. It’s a Lenovo Thinkpad Z16 with a Radeon graphic card.

**Comment by jacobgkau** [comment] 2023-12-28 21:29
@bastouf According to the [Lenovo product page](https://www.lenovo.com/us/en/p/laptops/thinkpad/thinkpadz/thinkpad-z16-(16-inch-amd)/len101t0037#tech_specs), the Thinkpad Z16 has integrated Radeon 600M graphics, but can also have optional dedicated Radeon RX6500M graphics. Do you know which one(s) you're experiencing the issue with?

**Comment by lwasyl** [comment] 2023-12-29 00:53
> If anyone else does experience this on bare metal hardware, the specific GPU(s) you're using would be relevant information.

Just happened to me on a PC with Radeon 7900XTX

**Comment by arteka-dev** [comment] 2023-12-29 21:33
@jacobgkau I have the dedicated Radeon RX6500 (Rembrandt? - i don't know what is it).

I will try to explain with my poor english (🇨🇵) : 

Today  i have tried to connect my external screen and... it's ok! 

- I can type my password to decrypt, then i see the login prompt and can log in to my session.

- When i am logged in, the screen of my laptop came back to black screen but not the external screen. 
- Then i increase the screen brightness and my two screens work perfectly.

It's weird...

**Comment by bastouf** [comment] 2023-12-29 21:34
@jacobgkau  I have the dedicated Radeon RX6500 (Rembrandt? - i don't know what is it).

I will try to explain with my poor english (🇨🇵) :

Today i have tried to connect my external screen and... it's ok!

I can type my password to decrypt, then i see the login prompt and can log in to my session.

When i am logged in, the screen of my laptop came back to black screen but not the external screen.

Then i increase the screen brightness and my two screens work perfectly.

It's weird...

**Comment by lwasyl** [comment] 2023-12-30 17:03
For folks encountering this and looking for a workaround: if you don't want to downgrade mesa packages, you can switch to `amdgpu` drivers by commenting out the line in `/etc/modprobe.d/blacklist-amdgpu.conf` and rebooting.

**Comment by jfhack** [comment] 2024-01-01 05:27
I have a workaround, which utilizes a mix of the information already provided here, to revive a virtual machine. The steps are as follows, once you have entered the root shell from the `Advanced options for Pop GNU/Linux` menu (by pressing `Esc` at the very beginning of the OS) then in the `recovery mode`
After running the command `apt policy libegl-mesa0`, in the version table, the second option that it showed me was `23.0.4-0ubuntu1~22.04.1`
So in the same shell, I saved it in an environment variable, installed that version for `libegl-mesa0`, `libglapi-mesa`, `libgbm1`, `libgl1-mesa-dri`, and `libglx-mesa0` and then marked them to prevent their update

```bash
VER=23.0.4-0ubuntu1~22.04.1

apt install libegl-mesa0=$VER libglapi-mesa=$VER libgbm1=$VER libgl1-mesa-dri=$VER libglx-mesa0=$VER
apt-mark hold libegl-mesa0 libglapi-mesa libgbm1 libgl1-mesa-dri libglx-mesa0
reboot
```

**Comment by Temperche** [comment] 2024-01-04 10:49
I can confirm the issue with a server using ASPEED AST2600 BMC graphics (display hardware), no RADEON involved. When I put updating the mesa libraries on hold as recommended, the issue is resolved.

**Comment by leviport** [comment] 2024-01-04 15:18
I wonder if the 23.3.2 update will help: https://github.com/pop-os/mesa/pull/27

**Comment by cadayton** [comment] 2024-01-04 18:51
@jfhack post resolved the issue for me too.

I'm running POP!_OS on 2 VirtualBox VMs and both have this issue when performing a system update.  Lesson learned. Back up the VM prior to doing a system update.   I've been doing system updates for over the last year without any issues and just got lazy on this last one.

**Comment by gerddie** [comment] 2024-01-08 15:27
Can you post the output of `glxinfo -B`, `wflinfo  -p wayland -a gl` , or `wflinfo  -p glx -a gl` on a working installation to see what OpenGL renderer is actually expected to be used?

**Comment by lwasyl** [comment] 2024-01-08 15:50
This is on working installation using amdgpu driver:
```
➜  ~ cat /etc/modprobe.d/blacklist-amdgpu.conf 
# blacklist amdgpu

➜  ~ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: NAVI31 (radeonsi, navi31, LLVM 15.0.7, DRM 3.54, 6.6.6-76060606-generic) (0x744c)
    Version: 23.3.0
    Accelerated: yes
    Video memory: 24576MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 23245 MB, largest block: 23245 MB
    VBO free aux. memory - total: 31417 MB, largest block: 31417 MB
    Texture free memory - total: 23245 MB, largest block: 23245 MB
    Texture free aux. memory - total: 31417 MB, largest block: 31417 MB
    Renderbuffer free memory - total: 23245 MB, largest block: 23245 MB
    Renderbuffer free aux. memory - total: 31417 MB, largest block: 31417 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 24576 MB
    Total available memory: 56295 MB
    Currently available dedicated video memory: 23245 MB
OpenGL vendor string: AMD
OpenGL renderer string: NAVI31 (radeonsi, navi31, LLVM 15.0.7, DRM 3.54, 6.6.6-76060606-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.3.0-1pop0~1702935939~22.04~67e417a
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.0-1pop0~1702935939~22.04~67e417a
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.3.0-1pop0~1702935939~22.04~67e417a
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

➜  ~ wflinfo  -p wayland -a gl
zsh: command not found: wflinfo

➜  ~ wflinfo  -p glx -a gl
zsh: command not found: wflinfo
```

**Comment by gerddie** [comment] 2024-01-08 18:13
Just to make sure: This is what is reported in the VM guest?

**Comment by lwasyl** [comment] 2024-01-08 18:18
No, this is on a _regular_ PC with a Radeon graphics card, where I also had this issue — no VM involved

**Comment by leviport** [comment] 2024-01-08 18:50
[Mesa 23.3.2](https://github.com/pop-os/mesa/pull/27) has been released. Our testing shows that graphics in VMs should be fixed with this update. When someone with Radeon graphics in question has an opportunity to test, please share your results.

**Comment by lwasyl** [comment] 2024-01-08 22:46
I confirm that with 23.3.2 the issue seems to be resolved, I've blacklisted admgpu drivers again and everything works fine :+1: This is on non-VM using Radeon 7900xtx

```
➜  ~ cat /etc/modprobe.d/blacklist-amdgpu.conf 
blacklist amdgpu

➜  ~ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: NAVI31 (radeonsi, navi31, LLVM 15.0.7, DRM 3.54, 6.6.6-76060606-generic) (0x744c)
    Version: 23.3.2
    Accelerated: yes
    Video memory: 24576MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 23751 MB, largest block: 23751 MB
    VBO free aux. memory - total: 31659 MB, largest block: 31659 MB
    Texture free memory - total: 23751 MB, largest block: 23751 MB
    Texture free aux. memory - total: 31659 MB, largest block: 31659 MB
    Renderbuffer free memory - total: 23751 MB, largest block: 23751 MB
    Renderbuffer free aux. memory - total: 31659 MB, largest block: 31659 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 24576 MB
    Total available memory: 56295 MB
    Currently available dedicated video memory: 23751 MB
OpenGL vendor string: AMD
OpenGL renderer string: NAVI31 (radeonsi, navi31, LLVM 15.0.7, DRM 3.54, 6.6.6-76060606-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.3.2-1pop0~1704238321~22.04~36f1d0e
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.2-1pop0~1704238321~22.04~36f1d0e
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.3.2-1pop0~1704238321~22.04~36f1d0e
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by leviport** [comment] 2024-01-08 22:53
Excellent, thanks for testing! I'll close this as resolved, but it can be reopened later if needed.

**Closed as completed by leviport** 2024-01-08 22:53 UTC
